# Site settings
title: Online News Packages
description: UC Berkeley Graduate School of Journalism. Spring 2015.
baseurl: "/15spring-onlinepackages" # the subpath of your site, e.g. /blog/
url: "http://ucbsoj.github.io/" # the base hostname & protocol for your site


# Build settings
markdown: redcarpet
redcarpet:
  extensions: [smart, tables]
highlighter: true
collections:
  lessons:
    output: true
    permalink: /:path/
